# Generated by Django 3.0.4 on 2022-04-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_id', models.IntegerField()),
                ('village_name', models.TextField()),
                ('village_boundary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('data', models.TextField()),
                ('city', models.TextField()),
                ('confirm', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('suspect', models.IntegerField()),
                ('confirm_add', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('case_num', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('village_name', models.TextField(blank=True, null=True)),
                ('relation', models.TextField(blank=True, null=True)),
                ('confirm_date', models.TextField(blank=True, null=True)),
                ('track', models.TextField(blank=True, null=True)),
                ('vehicle', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VillageData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('village_name', models.TextField()),
                ('village_boundary', models.TextField()),
                ('confirmed', models.IntegerField()),
                ('name', models.TextField()),
                ('closed_time', models.TextField()),
                ('opend_time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VillageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.TextField()),
                ('confirmed', models.IntegerField()),
                ('closed_time', models.TextField()),
                ('opend_time', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
        ),
    ]
